### ISSUE TITLE
[1.15.2] Crash while loading with Double Slabs mod

### ISSUE THREAD

**Issue by xAlicatt** [PianoManu/BlockCarpentry#12]
Crash on loading modpack. Doesn't happen with Block Carpentry installed, does happen when it is installed. 

Crash log: https://paste.ee/p/qoNjp

Block Carpentry ver: 0.8.1 (has happened with the last few versions as well)
Double Slabs version: 2.11.7

**Comment by PianoManu** [comment]
Hey xAlicatt, please update your Double Slabs mod to version 2.11.8. That should fix it, because the Double Slabs dev has already fixed it, see https://github.com/CJMinecraft01/DoubleSlabs/issues/112

**Comment by xAlicatt** [comment]
Thank you for the update...definitely still getting the crash with the new version. I will post over on Doubleslabs 👍
